### ISSUE TITLE
Ledger device unreachable. Make sure the device is…unlocked and with the correct application opened.

### ISSUE THREAD

**Issue by mandelmonkey** [LedgerHQ/ledgerjs#112]
Hi
I am using the latest btc app ver 1.2.3 and nano s firmware 1.4.1 chrome Version 64.0.3282.186 (Official Build) (64-bit) on Mac OS

I am trying to get the address on the browser using the following code but I get the error

```Ledger device unreachable. Make sure the device is…unlocked and with the correct application opened.```

previously browser mode had to be set however in the new app the option is not available (I heard it was not needed anymore)

Cable seems to be ok, I can use the chrome btc app no problem

```
    if (TransportU2F.isSupported()) {

      TransportU2F.create().then(function(transport) {

        const btc = new Btc(transport);

        btc.getWalletPublicKey("44'/0'/0'/0").then(function(address) {

          console.log(address);

        }).catch(function(error) {

          console.log(error);

        });
      }).catch(function(error) {

        console.log(error);

      });
    }
```

**Comment by gre** [comment]
@mandelmonkey yes, we are aware of the problem, there currently is an issue exclusively affecting communication of U2F with the BTC app on the latest firmware. We are working on the fix and a new btc app should get release ASAP. Let's leave the issue opened and we'll get back to you when it's fixed

**Comment by mandelmonkey** [comment]
awesome! just wanted to check if I was doing something wrong, is it an issue on the btc app side? if so is there a branch of the btc I could use?

**Comment by gre** [comment]
well, is it an issue on the hardware app (not having u2f working properly), not on the JS side. so nothing you can easily do for now

**Comment by mandelmonkey** [comment]
so its an issue on the blue-btc-app? I am using my own fork of the app so if there  is a branch or pull request for a fix would be handy to see, if not I can wait for the master branch to be updated :-)

**Comment by gre** [comment]
oh neat! no idea where and what the bug is, that's a bit beyond my expertise, as it's using the new firmware SDK I'm not even sure a previous version of the app would work 🤔 (maybe?). I guess better wait the fix to come, unless it's urgent for you & you want to figure it out, but otherwise they are working on it and it probably should get released next week.

**Comment by roosmaa** [comment]
I did some digging into this, wrote about it in the Slack #ledgerjs channel, but here's a copy-paste of it:

> so first of all, I think why ETH still works is because the ETH app (at least the repo) hasn't been migrated to the new U2F library bundled in the SDK 1.4.1
> 
> have been stepping through what happens in the chrome extension, the empty buffer apdu sign request is sent to ledger and 0x6700 (wrong length) is returned - as expected by reading the code. But then the chrome extension decides it's time to call the enroll command
> 
> ```    // When a device yields an idempotent bad key handle error to all sign
>     // challenges, and this is a sign request, we don't want to yield to the
>     // web page that it's not enrolled just yet: we want the user to tap the
>     // device first. We'll report the gnubby to the caller and let it close it
>     // instead of closing it here.
> ```
>
> so now the extension sends the enroll command over to ledger, which doesn't really have a good answer to it and returns 0x6F00 (internal error), which the chrome extension happily ignores which causes the enroll command to never get that response, thus at some point the whole original noop call timeouts. thus giving a false positive of the ledger dongle not being connected, where in reality it is.
> 
> Now with ETH app, which still uses the old U2F code (the one that got copy-pasted to every app), the behaviour is different. Instead of returning an error about length, it returns 0x6A80 (bad key handle) and the chrome extension doesn't attempt to do any enrolling and returns the error to ledgerjs, thus the "handshake" fails without the timeout, thus rest of the code is executed

**Comment by plumex** [comment]
nope, latest bitcoin 1.2.4 didn't fix the prob(tested with ledgerjs/packages/example-browser/hw-transport-u2f v4.7.0). I guess it's not relate with APP, even hw-transport-u2f.list() can not get device list correctly.

**Comment by gre** [comment]
we'll investigate on it today

**Comment by gre** [comment]
@roosmaa thanks for investigation :)

ok so the issue is that U2F is a bit more strict on what it accepts and sending a dummy (0, 0, 0, 0) apdu no longer works like it used to do, probably because we don't define a ScrambleKey. However, if sending (0, 0, 0, 0) with the BTC scramble key, while being on the btc app, it works properly.

- **on the short term**, we are going to temporarily disable the "handshake" mechanism of TransportU2F's open(). We will release a patch, probably today to fix this present issue.
- **on the long term**, we are going to rethink the architecture, please see below if interested by more details.

## **future plan** (draft raw thoughts)

*These are draft thoughts, my apologies if this idea list is a bit messy.*

I've discussed with @amougel  & @btchip and I think we will have to rethink the architecture of our JS libraries. We need to make our libraries reflect more what really happens on the device: the fact each app have its own lifecyle & its own channels (hid, u2f, ble,..). For instance, when you switch from App to the Dashboard (or reversely) there is actually disconnect & connect event happening under the hood, because it's like another device. This is by design and our JS libs need to embrace this hardware choice.
In current architecture of the libs you need to create a transport and only then you can use it in an app lib, like create a `new AppBtc(transport)`. It have some architecture flaw, because under the hood we actually need to mutate the transport with `setScrambleKey` when communication happen in a given app. Also the fact that nothing prevent you from doing another `new AppEth(transport)` at the same time does not reflect much what you really need to do with a transport. ideally you create a transport from an app, do something with this app, and close that transport because you are done.

So I think we will move to another architecture when you need both to know the transport and the app context to use.

Like: `create(TransportU2F, AppBtc)`  (create name to be changed) would returns a Promise of an API you can use to communicate to the AppBtc via U2F.

We would also have a `Dashboard` that is the "main screen" context, and it would provide all the API functions we can do in this context (like installing an app, listing apps, setting/getting device names, etc etc)

The "context provider", that `AppBtc`, would probably have to define a bunch of things like:
- a "ping" APDU call we would use for the handshake. at the same time, it would actually be wise to get the app version. We will also have in the future a check to ensure the app is actually the correct one you expect (AppBtc needs to check the btc app is opened on the device)
- exposes a `(transport, contextInfos) => API` function, that creates all the available API (bunch of functions) with a given transport instance. contextInfos would contains things like the app version so we can do feature branching at this time based on the version.

> the thing returned by the create() function above needs to be specified. One thing that might be convenient is a way to switch to a new context. like `.switchTo(AppEth)`, and then it returns a promise as well (it might help some steps because we don't need to create again a Hid instance afaik? not even sure)

**Comment by gre** [comment]
patch v4.7.2 should fix the issue. as said above, short term solution is to disable the handshake (meaning at open() time, we don't have guarantee the ledger device is actually here, only the first time you something (getting address,etc..) will be the real guarantee of that.

**Comment by mandelmonkey** [comment]
great thanks, can confirm patch is working

**Comment by alejoamiras-coinfabrik** [comment]
@gre that draft idea sounds great. When looking into the open() function I saw that when we open an app it sends a 'remove' event, and then a new 'add' and I thought it was a bug. Great to know it comes from the hardware architecture. 
Hope that draft comes to light on the near future. Great work +1
