### ISSUE TITLE
Compatibility with firmware 1.4?

### ISSUE THREAD

**Issue by hippias** [LedgerHQ/ledgerjs#126]
Hi there,

I have some issues interacting from the browser with your U2F lib since I updated to firmware version 1.4. The only error I get is: "Failed to sign with Ledger device: U2F TIMEOUT".
But I have another Ledger with firmware version 1.3 installed and it works properly, I can see the APDU exchanges.
The Ledger Web Tool at https://ledgerhq.github.io/ledger-wallet-webtool/ seems to behave likewise.

FYI I am using the latest version of packages hw-transport-u2f and hw-app-btc which is 4.7.3.

Is that an expected behaviour and do I have to make some config tricks? 

Your help would be much appreciated!

BTW: I had to find a thread on Reddit to learn that browser support is a default and not proposed as an option anymore. Despite this article updated 18 hours ago which doesn't mention this change from 1.4: https://support.ledgerwallet.com/hc/en-us/articles/115005198565-What-is-the-Browser-support-option-made-for-

**Comment by gre** [comment]
@hippias thanks for the issue,
on which application are you trying this? BTC app?
can you also check you have the latest BTC app installed on the device? if you go to settings>about, does it say 1.2.4 ?

just to double check, make sure this returns 4.7.3:
```
npm ls @ledgerhq/hw-transport-u2f
```

because the bug you mentioned was definitely existing before 4.7.3

I just tested on our "example-browser" app and it appears to work.

**Comment by hippias** [comment]
@gre It works now I was using 1.2.3, thanks for your quick reply!

The Ledger Manager GUI was not that explicit concerning the update status.

Best regards
