### ISSUE TITLE
Support concurrent requests via queuing semaphore instead of exclusive lock.

### ISSUE THREAD

**Issue by MicahZoltu** [LedgerHQ/ledgerjs#336]
Currently, LedgerJS uses a primitive lock to prevent two requests from hitting the ledger at the same time.  When a request is sent to the ledger a lock is acquired and if anything tries to access the ledger before that returns an exception will be thrown.  See the following code for the current flow:
```typescript
let lock = null
async sign(...): Promise<Signature> {
  try {
    if (lock) throw new Error(`Ledger Device is busy (lock ${lock})`)
    lock = 'sign'
    return await innerSign(...)
  } finally {
    lock = null
  }
}
```

The problem with this is that the following code will fail, even though there is nothing particularly wrong with it (note: example is a bit contrived for simplicity, in a more complex app there may be multiple code paths that lead to signing and the resolution isn't as simple as just awaiting each inline):
```typescript
const signature = sign(...)
const signature = sign(...) // exception thrown here
await signature
await signature
```

This can be resolved by using a queueing semaphore instead.  The simplest way to do this would be to just use something like https://www.npmjs.com/package/semaphore-async-await, though you could roll your own without too much work.  Here is what the same code would look like with a semaphore instead:
```typescript
const lock = new Semaphore(1)
async sign(...): Promise<Signature> {
  try {
    await lock.acquire()
    return await innerSign(...)
  } finally {
    lock.release()
  }
}
```

In this case, the call to `await lock.acquire()` will not return until the previous call to `sign` finishes (the finally block releases the lock).  Using this code, the user can freely queue up as many sign requests as they want (or `getAddress` calls or anything else that shares the Semaphore).  The library will simply not resolve the sign promise until prior sign requests finish and then the awaited sign request is finished.

----

If something like this is desirable, I may be interested in submitting a PR to implement it in the eth-app, as it is currently causing me pain as I have to create a wrapper around the Ledger library and use that everywhere to avoid call failures when things happen concurrently.

**Comment by gre** [comment]
One way to solve this as you said is to use a semaphore, another way is to use this kind of queuing code:

```js
let queue = Promise.resolve()
const withDevice = devicePath => job => {
  const p = queue.then(async () => {
      const t = await retry(() => TransportNodeHid.open(devicePath), { maxRetry: 2 })
      try {
        const res = await job(t).catch(mapError)
        return res
      } finally {
        await t.close()
      }
  })
  queue = p.catch(() => null)
  return p
}
```

which used to do what Live Desktop was doing: 
https://github.com/LedgerHQ/ledger-live-desktop/blob/v1.1.11/src/helpers/deviceAccess.js#L38-L39


More recently we've switched to a more complex code because we usually use Observable instead of promises for our jobs.

https://github.com/LedgerHQ/ledger-live-common/blob/master/src/hw/deviceAccess.js#L68-L70

---

There are many ways to solve this and the current take of ledgerjs is you have to deal with that and it's not ledgerjs to solve this for you. The current behavior that you describe (throwing an exception) only exists to prevent race condition as early as possible, if we don't have this failsafe, we can end up with really cryptic errors or sometimes very hard to understand bugs (and it also depends on the transport itself).

If we do a choice like using a semaphore or a queue, it means allowing that it's fine that the call can happen after the previous job is finished. It's not always what you want as an API, maybe you want a direct answer instead of having something that queue up. Typically problem that queuing/semaphore can have is that you need to be careful about nesting them and also about redeeming them, otherwise you quickly end up in locking system that makes it look like the device never answer again but in fact it's the logic that have locked.

One other aspect is that, sometimes you want to let to the user "cancel" the pending job, that's why we have moved to Observable a bit everywhere in Live codebase. For instance, you can now cancel an app install or a scan accounts,.. a simple semaphore/queueing don't allow this easily.

There is even another way to solve this: you can have safeguard in your code to make sure the UI makes it impossible to have race condition, guaranteeing things happen once at a time at the UI level. for instance by making a GET ADDRESS button as soon as you click it "disabled" while the call is happening and only enabled again when it's finished so it can't be clicked twice.


**So basically the short answer is we try to not be too opinionated on this because it is a complex problem and depends on the usecases.** It makes hw-app-* libraries a bit lower level than what you can expect. In the future, we consider making these even low level in that they could be just functions that takes a transport and do the job with it. It is what we have been doing recently in all these functions you can find here: https://github.com/LedgerHQ/ledger-live-common/tree/master/src/hw

Minimal example:

```js
// @flow
import Transport from "@ledgerhq/hw-transport";
export default async (transport: Transport<*>): Promise<string> => {
  await transport.send(0xe0, 0x50, 0x00, 0x00).catch(() => {});
  const res = await transport.send(0xe0, 0xd2, 0x00, 0x00);
  return res.slice(0, res.length - 2).toString("utf-8");
};
```

short functions, simple code, can easily be extended by creating more of them. This is what I think future version of hw-app-* libraries can just be, more modular and making more freedom for different usecases. People are free to build abstractions on top of it.

**Comment by gre** [comment]
another answer on this is I would rather prefer our codebase to be refactored in a more clear and maintainable codebase, to the bare minimum of just being these `(transport, ..)=>Promise<..>` functions so we can really focus on making them (and fixing them, adding more of them). Because we have many work to be done still in these functions, typically refactoring the hw-app-btc should be our main focus for ledgerjs maintainers.

Solving the concurrency problem can be solved by a dedicated library, typically a library like live-common that makes everything works all together (multi-transports, multi-apps, queuing system,...).
