### ISSUE TITLE
404 docs

### ISSUE THREAD

**Issue by DalderupMaurice** [LedgerHQ/ledgerjs#346]
Currently the following URL returns a 404.
http://ledgerhq.github.io 

This is can be found right in the README of hw-transport-node-hid (and other locations as well - most likely):
https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-node-hid

It would be helpful if the docs were up

**Comment by gre** [comment]
The doc was intentionally removed because it was literally the exact same thing as what you find in README. this doc was in fact confusing because it was containing a merged version of all library, was not segmented per library like we have in README.

If later, we wrote more article/gitbook like documentation, we could revive something.

**Comment by gre** [comment]
We need to remove all reference of this doc. good point.

**Comment by gre** [comment]
fixed by https://github.com/LedgerHQ/ledgerjs/commit/92a0aa5cc82c72b808cb520b7c2b2a8a86b8060e
