### ISSUE TITLE
To get list of btc addresses from ledger.

### ISSUE THREAD

**Issue by wAISw** [LedgerHQ/ledgerjs#444]
Hello! 
Is it possible to get a list of addresses using @ledgerhq/hw-app-btc without passing the derivation path or get information about all accounts with one call?
My task is, to get the user ability to choose one of many existed addresses on his ledger.
I need to implement it in a react app.

**Comment by gre** [comment]
You might want to check https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki specification. and especially the "Account discovery" section. The short answer is you have to use paths to derivate addresses with a ledger device, there is no such "list all btc addresses" available (and there is ultimately an infinite number of addresses). The list of used accounts is not something even the device can know because it requires you to check addresses on explorer to check if there are transactions associated to it.

Also be aware it's not recommended to implement a "pick from a list of addresses" but ideally you need to present to the user the "next address" that is not used.

Best regards,
gre

**Comment by wAISw** [comment]
Thank you for the fast answer.
In the library, @ledgerhq/hw-app-btc existed the method `getWalletPublicKey`
and if I'm not mistaken, I have to call it twice to get information about two accounts on the ledger wallet, like this:
`
const accountOne = await btc.getWalletPublicKey(`m/44'/0'/0'/0`)
const accountTwo = await btc.getWalletPublicKey(`m/49'/0'/0'/0`)
`
and the leger wallet will ask a user twice.
Am I right?
