### ISSUE TITLE
Project Naming

### ISSUE THREAD

**Issue by georgedrummond** [LedgerHQ/ledgerjs#46]
@btchip can we get some consistency on the project naming?

* Git Repo - `ledgerjs`
* Repo Title - `ledger-node-js-api`
* NPM Name - `ledgerco`

I'm concerned that someone malicious could squat on those package names since they **are available and not registered**. This could lead to some serious and malicious issues with developers using the wrong packages in their Ledger integrations.

**Comment by gre** [comment]
good point.

as we are about to merge https://github.com/LedgerHQ/ledgerjs/pull/37.

- `ledgerco` will become a deprecated library. we'll add a deprecate message in the README and on the npm package. Since we now have libraries published on NPM in our own scope `@ledgerhq/*`, this will address the npm name squatting problem.
- `ledgerjs` can't be taken because `ledger.js` already exist (and have nothing to do with crypto)
- `ledger-node-js-api`, i've taken it with a redirection & deprecation message.


BTW, at some extend, there is nothing really serious malicious code could do to your fund, because the private key is not exposed out of the device, and user should always validate on the device. But still it can be annoying and we'll watch this carefully.

Regards
