### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: btc.serializeTransactionOutputs is not a function

### ISSUE THREAD

**Issue by ambush276** [LedgerHQ/ledgerjs#482]
Just upgraded to the latest versions:

@ledgerhq/hw-app-btc@5.12.0
@ledgerhq/hw-transport-node-hid@5.12.0

and now i am getting this error 
```(node:41119) UnhandledPromiseRejectionWarning: TypeError: btc.serializeTransactionOutputs is not a function```

below is the code i am using to create the txn:

``` 
- utxo/txin are in hex already

-- Note: In earlier versions such as hw-app-btc@4.11.0 i did not have this error.

const regeneratorRuntime = require("regenerator-runtime");
var Transport = require("@ledgerhq/hw-transport-node-hid");
var AppBtc  = require("@ledgerhq/hw-app-btc");

const getBtcAddress = async () => {
const transport = await Transport.default.create();
  const btc = new AppBtc.default(transport);
  const tx1 = await btc.splitTransaction(utxo);
  const tx2 = await btc.splitTransaction(txin);
  const outputscript = btc.serializeTransactionOutputs(tx1).toString("hex");

.....

```

**Comment by ambush276** [comment]
nobody has seen this issue before. It seems like this is a core issue?

**Comment by gre** [comment]
serializeTransactionOutputs is no longer part of `AppBtc` instance because it was assumed to be a private internal helper.

It is still available under `/lib/serializeTransaction`, probably doing `const {serializeTransactionOutputs  } = require("@ledgerhq/hw-app-btc/lib/serializeTransaction")` and then `const outputscript = serializeTransactionOutputs(tx1).toString("hex")`

https://github.com/LedgerHQ/ledgerjs/blob/2ab3791d5ada44e9ce0f920b4df2db3c585b8d44/packages/hw-app-btc/src/serializeTransaction.js
