### ISSUE TITLE
@ledgerhq/web3-subprovider incorrect dependency for @ledgerhq/hw-transport-u2f 

### ISSUE THREAD

**Issue by Matko95** [LedgerHQ/ledgerjs#527]
When installing @ledgerhq/web3-subprovider
`Couldn't find any versions for "@ledgerhq/hw-transport-u2f" that matches "^5.23.0"`
The latest version for hw-transport-u2f is 5.22.0

**Comment by gre** [comment]
good catch. 

dev note: the problem being that we deprecated @ledgerhq/hw-transport-u2f and put it "private" so lerna don't republish it, but it still managed to bump it i guess. i'll see if we can find an easy solution, otherwise we'll still have to publish bump of u2f and deprecate individually ..

**Comment by aydnep** [comment]
any reasons why you deprecate hw-transport-u2f what I see it has the best browser/os support in compare with webUSB

**Comment by gre** [comment]
U2F is a technology that is not meant for bi-directional communication protocol. It's a hack in the first place that we use it for this (apart from the usage in the FIDO app) but also it was for a long time the only way to do so in a web browser.
Now that webusb and webhid are coming as an emerging standard, we tend to favorize them over u2f. Using U2F is not a good bet for the future, because, like any hack, it's a workaround that might eventually really break as we use it for something it's not made for.

U2F is limited too in that you can't know when the device is disconnected, it's fire and forget, there are timeout problems and on top of that connectivity issues on Windows (differ between materials/drivers).
