### ISSUE TITLE
Needs error when issuing two commands concurrently on accident

### ISSUE THREAD

**Issue by sgehrman** [LedgerHQ/ledgerjs#83]
I had a very annoying bug where I was accidentally getting the public key and  issuing a sign transaction before the getpublickey call returned.  It would succeed or fail randomly and it took forever to track down.  It would be great if the ledger would have returned an error alerting me to the fact that I was trying to sign before the getpublickey returned. It also worked fine for u2f, but put my ledger in weird state for node-hid.

**Comment by gre** [comment]
good point.
I believe this happens when getPublicKey is called in the middle of a signing workflow.
the signing workflow asynchronously chain a few APDUs so there is a race condition in the middle if getPublicKey is called.

We probably need to have this protection on all the methods of the app-* libs, basically we need a semaphore on the transport to lock at the beginning and release at the end.

@btchip what do you think of such protection mechanism on the lib side?
