### ISSUE TITLE
U2F exchange hangs after more than 30 seconds

### ISSUE THREAD

**Issue by lenondupe** [LedgerHQ/ledgerjs#94]
If you set the exchange timeout on the u2f transport to more than 30 seconds (the default) and wait more than 30 seconds (but less than the custom timeout) before approving the transaction, the exchange will hang. In debug mode it shows no packets are received anymore.

Steps to reproduce:

First set the exchange timeout on the transport to more than 30 seconds. For instance 45:

```Index: packages/test/src/runTests.js
===================================================================
--- packages/test/src/runTests.js	(revision eb96fd57f3e8504741a750a1f5e324c8b07d84bd)
+++ packages/test/src/runTests.js	(revision )
@@ -120,6 +120,7 @@
     ][i % 3];
     let transport = await createTransport(Transport);
     transport.setDebugMode(true);
+    transport.setExchangeTimeout(45 * 1000);
 
     if (step.name) {
       console.info("Running test " + step.name);
```

Then build and run the browser tests. When the device asks for confirmation during the `testBtc2` test wait for more than thirty seconds but less than 45 seconds.

Expected: the test passes and the script continues to the next test.

Actual: Nothing happens. No response is logged on the javascript console. After 45 seconds however a TransportError is logged: `U2F TIMEOUT`.

**Comment by roosmaa** [comment]
This sounds like an issue I solved for my Nano (the currency) app. The underlying problem here is that the Chrome U2F extension has a hard-coded timeout of 31 seconds (if memory serves). When it hasn't received an answer from the dongle during that time it will kill the request.

There is a way to allow for longer requests, but it requires support from the app running on the Ledger device. The trick is to return the BUSY U2F status code before the 31 second hard-timeout. That will force the U2F extension to retry the request. But this also means that the Ledger app needs to be able to map the 2nd incoming request to the 1st one that's still ongoing (or that recently finished).

I guess the best way would be to just document this in `setExchangeTimeout` and warn ledger.js users that most apps out there don't handle timeouts of more than 30 seconds well.

Here are the relevant Nano [currency] app code snippets that allow for longer requests:

- Returning the BUSY status code - [roosmaa/blue-app-nano/src/main.c#L40-L53](https://github.com/roosmaa/blue-app-nano/blob/edaa43c/src/main.c#L40-L53)
- Triggering a timeout before the 31 second force-kill - [roosmaa/blue-app-nano/src/main.c#L125-L133](https://github.com/roosmaa/blue-app-nano/blob/edaa43c/src/main.c#L125-L133)
- Mapping the request back to the ongoing one - [roosmaa/blue-app-nano/src/nano.c#L46-L65](https://github.com/roosmaa/blue-app-nano/blob/edaa43c3488e91a9066c964aed5fb6ea1cf01c42/src/nano.c#L46-L65)

**Comment by gre** [comment]
it will be more and more recommended to use WebUSB/WebHID over U2F.
